#!/usr/local/bin/perl
#
#
#

use Fcntl;

$tty="/dev/cua0";

sysopen(DEV, $tty, O_RDWR) || die "$dev: $!";

system("/bin/stty 19200 -opost ixoff -ixon -ixany -icanon -echo  < $tty");
system("/bin/stty -a < $tty 1>&2");

print STDERR "stty done\n";

while(1) {
	$_ = <DEV>;
#	chomp($_);
#	print "$_\n";
	
	print $_;
}

close(DEV);

